Update key spanish commemoration_of_all_the_faithful_departed
pejulian/romcal pull request #470
Opened 2023-11-02 10:03 UTC by miguelms95

commemoration_of_all_the_faithful_departed to oficial CEE translate.

2023-11-05 19:17 UTC, tukusejssirs requested changes
@miguelms95, thanks for your PR! :pray:

@emagnier, we could merge this after adding a source for the changed celebration name.

2023-11-05 19:17 UTC, tukusejssirs commented on lib/locales/es.ts
> +    commemoration_of_all_the_faithful_departed: 'Conmemoración de todos los fieles difuntos',
@miguelms95, as we recently started adding source comments, we need now to add a source for all changes. I have found [here](https://www.conferenciaepiscopal.es/comisiones/liturgia/) some Spanish Ordos, so I have added one of them as the source of this celebration name.

```suggestion
    commemoration_of_all_the_faithful_departed: 'Conmemoración de todos los fieles difuntos',  // src: https://www.conferenciaepiscopal.es/wp-content/uploads/2022/11/CLP-y-salmos-responsoriales-2022-2023_internet.pdf#page=342
```

2023-11-28 12:17 UTC, miguelms95 commented
Hi @tukusejssirs, good practice to add the source. I've just added your suggested change, that is according the Spanish CCE.

2023-11-28 14:23 UTC, tukusejssirs approved these changes

2023-11-30 18:10 UTC, merged