fix(build): standardize lint, improve some types
pejulian/romcal pull request #479
Opened 2024-03-02 20:02 UTC by TobiTenno

closes #383 

- update eslint to use airbnb (a very standard rule) for linting base
- lint more stuff by using overrides instead of not linting everything
- fix an (as far as i've seen) unreported bug around a type in a string
	- `PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D`

2024-03-02 20:02 UTC, TobiTenno commented
ooof, i forgot to make sure i ran tests locally. back to draft!

2024-03-02 20:31 UTC, TobiTenno commented
@emagnier @tukusejssirs now that i've gotten the lint parts, i'm rather confused at this part, as i've not seen tmp built before build is run, so it's expecting some sort of tmp file to exist.

could one of you make it clearer for me?

2024-03-02 22:32 UTC, tukusejssirs requested changes
You have run the new ESlint config and it made some errors in the build script. The proposed two reverts sortes this out, although you still need to fix the ESlint errors. Until those are fixed, you need to run `pnpm clean && node -r ts-node/register scripts/build.ts` in order to circumwent running the `prebuild` script which checks the linting of the code, but fails.

2024-03-02 22:32 UTC, tukusejssirs commented on scripts/build.ts
> +    `),
```suggestion
    await formatCode(
      `import { toPackageName } from "../../lib/utils/string";\n\n` +
        `export const LOCALE_VAR_NAMES: string[] = ${JSON.stringify(localeNames)};\n\n` +
        `export const LOCALE_IDS: string[] = LOCALE_VAR_NAMES.map(c => toPackageName(c));\n`
    ),
```

2024-03-02 22:32 UTC, tukusejssirs commented on scripts/build.ts
> +    `),
```suggestion
    await formatCode(
      `import { toPackageName } from "../../lib/utils/string";\n\n` +
        `export const CALENDAR_VAR_NAMES: string[] = ${JSON.stringify(calendarNames)};\n\n` +
        `export const CALENDAR_PKG_NAMES: string[] = CALENDAR_VAR_NAMES` +
        '.map(c => `@romcal/calendar.${toPackageName(c)}`);\n',
    ),
```

2024-03-03 17:34 UTC, emagnier commented
Hello both, thank you @tukusejssirs and @TobiTenno for your contributions and thanks @TobiTenno for this PR! I'm indeed quite busy and have limited time available lately, but I'll take a look at your PR asap 🙏

2024-03-03 20:00 UTC, TobiTenno commented
> Hello both, thank you @tukusejssirs and @TobiTenno for your contributions and thanks @TobiTenno for this PR! I'm indeed quite busy and have limited time available lately, but I'll take a look at your PR (and all the other recent PRs) asap 🙏

I'd love to help out more, it'd be great if @tukusejssirs could tag-team PRs to get them through so we could help out and move things along faster.

we'd like to get all the verifications more stable, etc, and be able to update the public page so we don't have the kind of lag we're seeing now on fixes getting uploaded

2024-03-03 22:36 UTC, tukusejssirs commented
> it'd be great if @tukusejssirs could tag-team PRs

@TobiTenno, what do you mean by _tag-team_ PRs? PRs tagged with `team` label?

2024-03-03 23:26 UTC, TobiTenno commented
> > it'd be great if @tukusejssirs could tag-team PRs
> 
> @TobiTenno, what do you mean by _tag-team_ PRs? PRs tagged with `team` label?

sorry, it's an American colloquialism for pair-coding or working together to make sure we get through all of it

2024-03-03 23:28 UTC, TobiTenno commented
@emagnier simply, it'd be great if we could have the ability to get a bit more through and done and have a wider write-enabled contributor base (like, even just @tukusejssirs) so that we can get fixes through and released

2024-03-09 20:36 UTC, tukusejssirs commented
> @tukusejssirs sorry, it's an American colloquialism for pair-coding or working together to make sure we get through all of it

Thanks for the explanation! I’ve never heard it before. :wink:

> it'd be great if we could have the ability to get a bit more through and done and have a wider write-enabled contributor base (like, even just @tukusejssirs) so that we can get fixes through and released

Well, I have some rights (I can merge changes, though I usually let the maintainer [in this case Etienne] to do it). I don’t consider myself worthy of being an actual maintainer (due to my inexperience and lack of time I can devote to romcal). That said, I don’t have full permissions on the repo (I am only a [member of romcal org](https://github.com/orgs/romcal/people)). I think that might be worthy to have full access to romcal repo (i.e. to become an owner) which I’d use rarely. WDYT, @emagnier?

Also, it seems to me that @TobiTenno has some time to devote to romcal and he seems to me like he has enough experience to maintain romcal, therefore, I suggest to let him become a (co-) maintainer. WDYT, @emagnier?

2024-03-09 21:08 UTC, tukusejssirs approved these changes

2024-03-09 21:36 UTC, tukusejssirs commented
>     * fix an (as far as i've seen) unreported bug around a type in a string
>       
>       * `PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D`

This change is a bit outside of the scope of the #383, consider moving it to a separate PR. However, even if not moved to a separate PR, I’ll merge this branch tomorrow in the evening CET (~5-7pm UTC).

2024-03-10 16:23 UTC, TobiTenno commented
> > ```
> > * fix an (as far as i've seen) unreported bug around a type in a string
> >   
> >   * `PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D`
> > ```
> 
> This change is a bit outside of the scope of the #383, consider moving it to a separate PR. However, even if not moved to a separate PR, I’ll merge this branch tomorrow in the evening CET (~5-7pm UTC).

@tukusejssirs I'm happy to move it to help clarity and observability of the bug

2024-03-10 16:24 UTC, TobiTenno commented
> > > ```
> > > * fix an (as far as i've seen) unreported bug around a type in a string
> > >   
> > >   * `PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D`
> > > ```
> > 
> > 
> > This change is a bit outside of the scope of the #383, consider moving it to a separate PR. However, even if not moved to a separate PR, I’ll merge this branch tomorrow in the evening CET (~5-7pm UTC).
> 
> @tukusejssirs I'm happy to move it to help clarity and observability of the bug

sorry, I say that, but it's actually caught _because_ of the changes w/ #383, essentially it's the bug that got caught by linting/typing better, and removing it would cause a lint error that would make this fail CI

2024-03-10 16:53 UTC, tukusejssirs commented
> sorry, I say that, but it's actually caught because of the changes w/ https://github.com/romcal/romcal/issues/383, essentially it's the bug that got caught by linting/typing better, and removing it would cause a lint error that would make this fail CI

Okay, then it makes sense to keep it in this PR. :pray:

2024-03-10 22:40 UTC, merged