docs: add lint & prettier instructions to contributing
pejulian/romcal pull request #549
Opened 2024-05-06 00:47 UTC by TobiTenno

closes #548

2024-05-08 21:53 UTC, TobiTenno commented
@tukusejssirs @emagnier would appreciate a quick overview

2024-05-09 05:37 UTC, tukusejssirs requested changes

2024-05-09 05:37 UTC, tukusejssirs commented on CONTRIBUTING.md
> +We leverage typescript eslint and prettier to enforce code style. You can run the following command to check if your code is compliant:
```suggestion
We leverage TypeScript Eslint and Prettier to enforce code style. You can run the following command to check if your code is compliant:
```

2024-05-09 05:37 UTC, tukusejssirs commented on CONTRIBUTING.md
> +File formatting (prettier):
```suggestion
File formatting (Prettier):
```

2024-05-09 05:38 UTC, tukusejssirs commented
I have just some nitpicks, oyherwise this is good to go.

2024-05-09 14:38 UTC, TobiTenno commented
I don't think these make sense, given they're always referenced in code without title case. That said, I'll update it.

2024-05-09 14:41 UTC, tukusejssirs commented
> I don't think these make sense, given they're always referenced in code without title case. That said, I'll update it.

Why don’t you think they make sense? :thinking:

IMHO any name (e.g. personal name, program name) should be spelled (incl the case) the way the owner/author wants it. Therefore, if the author of Prettier spells the program name as _Prettier_ (with a capital initial letter), we should honour it.

2024-05-09 15:23 UTC, tukusejssirs approved these changes

2024-05-09 15:53 UTC, TobiTenno commented
@tukusejssirs I dismissed and would appreciate another review, as I changed how my references work to better indicate that i'm trying to reference the package names and _not_ the framework name.

As such, I titlecased Prettier where it is referenced as the framework, and code-blocked the names when referencing the scope & package names

2024-05-09 17:19 UTC, tukusejssirs approved these changes
Thanks, @TobiTenno! :pray:

Yeah, I have no problem with program/command names being cased as they would be run in a terminal when formatting them as code.

2024-05-09 17:25 UTC, merged