enh(calendar): separate easter vigil
pejulian/romcal pull request #550
Opened 2024-05-06 01:19 UTC by TobiTenno

closes #199

2024-05-06 11:08 UTC, tukusejssirs requested changes
I have a few change requests (related to your TODO code comments). The biggest issue I see is an unimplemented way to add celebration subtitles and/or Mass formulars (I am not sure if it is actually called a Mas _formular_ in English; it’d be awesome if you confirm it :wink:).

2024-05-06 11:08 UTC, tukusejssirs commented on lib/locales/en.ts
> +    easter_vigil: 'Easter Vigil',
What reference is needed? Do you mean a _source_ reference when the key value can be found?

---

In [`mr_en_2011_ed3_us`](https://drive.google.com/file/d/12aeIw1559RyEPlBpGf6_o6Me5NxqjoLR/view?usp=drive_link) (private link) on p339 (PDF page, don’t look at the printed page numbers), the name of the Sunday is `Easter Sunday of the Resurrection of the Lord`. Next on p341, we have `The Easter Vigil in the Holy Night`.

Now IMHO, a celebration name should be the same regardless whether it is celebrated in the eve of the solemnity or on the day. I think the vigil name (if any) should be added as a celebration subtitle (see #297). Note that in the future we might need to differentiate between celebration subtitles (as described in #297) and Mass formulars (which we didn’t implemented yet), and the Masses `in the vigil`/`at dawn`/`during the day` are actually Mass formulars of a particular celebration.

This needs to be further discussed, however, IMHO we should implement either #297 (which partially solves this issue) or Mass formulars (related to #20; this might be better suited to fix this particular problem).

2024-05-06 11:08 UTC, tukusejssirs commented on lib/locales/en.ts
> +    holy_saturday: 'Holy Saturday',
```suggestion
    holy_saturday: 'Holy Saturday', // src: mr_en_2011_ed3_us, Holy Saturday, p339
```

2024-05-06 11:08 UTC, tukusejssirs commented on lib/locales/pl.ts
> +    easter_vigil: 'Wigilia Wielkanocna',
[src](https://drive.google.com/file/d/1KQ0XEoiQjX79sR1mfRc6OaRfeoulPcv5/view?usp=drive_link)

```suggestion
    easter_vigil: 'Wigilia Paschalna', // src: Kalendarz liturgiczny Diecezji Tarnowskiej, Wigilia Paschalna, p135 (https://drive.google.com/file/d/1KQ0XEoiQjX79sR1mfRc6OaRfeoulPcv5/view)
```

2024-05-06 11:08 UTC, tukusejssirs commented on lib/locales/sk.ts
> +    easter_vigil: 'Veľkonočná vigília',
I need to tend to this. I want to check it in `mr_sk_2021_ed3` in my local church. Bear with me please.

2024-05-06 11:36 UTC, emagnier requested changes
This PR should not be merged, or at least not in its current state. Because it goes against what Romcal currently produces (`LiturgicalDay` vs. `Celebration`, which are not the same level of data and abstraction).

Indeed, it aligns with the comment I had written [here](https://github.com/romcal/romcal/issues/199#issuecomment-660554577) in 2020. However, in the meantime, the Romcal codebase and functionalities have evolved significantly.

And today, this PR goes against the points I mentioned here: https://github.com/romcal/romcal/issues/511.

I will take more time this evening to explain the reasons (as I'm not too available at the moment).

2024-05-06 12:45 UTC, TobiTenno commented on lib/locales/pl.ts
> +    easter_vigil: 'Wigilia Wielkanocna',
i'll reformat w/ a block comment

2024-05-06 12:46 UTC, TobiTenno commented on lib/locales/en.ts
> +    holy_saturday: 'Holy Saturday',
will do.... not sure we need to add a specific source for something that already exists

2024-05-06 12:46 UTC, TobiTenno commented on lib/locales/en.ts
> +    easter_vigil: 'Easter Vigil',
pretty much this one you just gave me

2024-05-06 12:51 UTC, TobiTenno commented
@emagnier 
If I shouldn't do this, we should close #199 as no longer needed and reopen once whichever issue we end up doing between #297/#20 (or both!), as it doesn't make sense in current context if there are still several parts to sort out the why and how, as the days we describe (and already have, the Holy Thursday split is not new) in #511 clearly already allows for this kind of exception, it just doesn't make it easy to create

2024-05-06 23:07 UTC, emagnier commented
I rather think that the spec of https://github.com/romcal/romcal/issues/199 needs to be redefined ([see my comment ](https://github.com/romcal/romcal/issues/199#issuecomment-2097052129) in this issue).

https://github.com/romcal/romcal/issues/297 and https://github.com/romcal/romcal/issues/20 are not in contradiction to this topic (and can be addressed separately).

About https://github.com/romcal/romcal/issues/511, it's not exactly the same thing, as Holy Thursday is the day when there's a change of liturgical season within the civil day (Lent to Paschal Triduum at evening mass). So, they have not the same metadata. Whereas Easter Vigils are intimately linked to Easter Sunday.

2025-05-19 22:36 UTC, emagnier commented
I think this PR should be closed.
The concept of `LiturgicalDay` absolutely needs to be preserved (it's the foundation for building the liturgical calendar) and shouldn't be mixed with the concept of `Celebration`.

The ability to output `Celebrations` (instead of `LiturgicalDays`) isn’t currently supported, but it would definitely be a feature worth adding.

2025-05-20 02:37 UTC, TobiTenno commented
@emagnier in the future, I'd update the ticket first to change the detail to somehow output celebrations, because that's pretty different than what was intended before. Since that's the desired go-forward, I agree, but i don't think this PR would've broken the concept of LiturgicalDay, personally.

2025-05-20 09:30 UTC, emagnier commented
Sorry, I may have been a bit too quick and radical here. You're right, it’s definitely possible to update the details of this PR while still preserving the concept of a `LiturgicalDay` (feel free to reopen it if needed, or start a new branch/thread, whichever you prefer).

That said, I can confirm that this change would have broken the concept as it stands, because the Easter Vigil and Easter Sunday both belong to the same *liturgical* day (in the strictly liturgical sense, not the civil 24-hour day starting at midnight). 

To avoid spreading the discussion too much, I'm responding more broadly here  [https://github.com/romcal/romcal/issues/199#issuecomment-2893634247](https://github.com/romcal/romcal/issues/199#issuecomment-2893634247), with a proposed better approach to tackle this topic.

2025-05-20 13:30 UTC, TobiTenno commented
well, _Liturgically_ Easter Saturday has no liturgies proper to it apart from the Easter Vigil. I agree that it would've added some distinctness, but i don't think this would've radically broken our concept. I'll revisit and try a different way

2025-05-20 14:13 UTC, emagnier commented
The Roman Rite indeed does not provide a Mass on Holy Saturday. So it's completely logical — and even important — that Romcal doesn't return anything for that liturgical day, in keeping with the spirit of the liturgy for that day and the rules of the Roman Missal.

The issue you're describing is mostly a display issue (being able to show the Easter Vigil on Saturday evening). So in this case, we shouldn't try to bend the concept of `LiturgicalDay`, which should remain as-is (as a low-level core layer). Instead, we should build a layer on top of `LiturgicalDay` that can also generate entities like `Celebration` or `Mass`, which can meet needs that are strictly calendrical (in the sense of the civil calendar) or practical (in terms of visual display or user presentation, outside of a purely liturgical concept). See my comment here for a proposal in that direction: [https://github.com/romcal/romcal/issues/199#issuecomment-2893634247](https://github.com/romcal/romcal/issues/199#issuecomment-2893634247)

2025-05-20 16:00 UTC, TobiTenno commented on lib/locales/sk.ts
> +    easter_vigil: 'Veľkonočná vigília',
@tukusejssirs whenever you have a chance, this would be most welcome, I'm planning on modifying the PR. not sure on the final direction yet, but these changes, i believe, will still be included.

2026-03-24 01:20 UTC, closed without merging