Fix/es translation
pejulian/romcal pull request #571
Opened 2024-06-04 12:26 UTC by miguelms95

fix our_lord_jesus_christ_king_of_the_universe and our_lord_jesus_christ_the_eternal_high_priest

2024-06-17 20:55 UTC, TobiTenno commented
@miguelms95 since everything from the first few commits was not valid, i dropped them off. lemme know if it seems like something's missing now, cause your old stuff already matched dev... i'm thinking they were old commits.

2024-06-17 20:56 UTC, TobiTenno commented
@emagnier @tukusejssirs your reviews would be appreciated!

2024-06-17 21:07 UTC, tukusejssirs requested changes
The celebration names are not cited carefully. Other then that, LGTM.

Thanks, @miguelms95 and @TobiTenno! :pray:

2024-06-17 21:07 UTC, tukusejssirs commented on lib/locales/es.ts
> +    our_lord_jesus_christ_king_of_the_universe: 'Cristo Rey del Universo', // src: https://textosparalaliturgia.blogspot.com/2014/09/misal-romano-jesucristo-rey-del-universo.html
The source says the celebration name is `Jesucristo, Rey del Universo`.

```suggestion
    our_lord_jesus_christ_king_of_the_universe: 'Jesucristo, Rey del Universo', // src: https://textosparalaliturgia.blogspot.com/2014/09/misal-romano-jesucristo-rey-del-universo.html
```

2024-06-17 21:07 UTC, tukusejssirs commented on lib/locales/es.ts
> +    our_lord_jesus_christ_the_eternal_high_priest: 'Nuestro Señor Jesucristo, Sumo y Eterno sacerdote', // src: https://textosparalaliturgia.blogspot.com/2014/05/misal-romano-jesucristo-sumo-y-eterno
The source says the celebration name is `Jesucristo, Sumo y Eterno Sacerdote`.

```suggestion
    our_lord_jesus_christ_the_eternal_high_priest: 'Jesucristo, Sumo y Eterno Sacerdote', // src: https://textosparalaliturgia.blogspot.com/2014/05/misal-romano-jesucristo-sumo-y-eterno.html
```

2024-06-17 21:46 UTC, TobiTenno commented
please stop making the title very long

2024-06-18 17:09 UTC, tukusejssirs requested changes
LGTM, thanks! :pray:

2024-06-18 17:10 UTC, tukusejssirs approved these changes

2024-06-18 17:10 UTC, merged